$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

properties:
  samples:
    type: string
  units:
    type: string
  #adapter:
    #type: string
    #pattern: "^[ACGT]+$"

  modules:
    type: object
    properties:
      gatk:
        type: string
      required:
        - gatk


  ref:
    type: object
    properties:
      genome:
        type: string
    required:
      - genome

  filtering:
    type: object
    properties:
      clines:
        type: string
      vqsr:
        type: boolean
      hard:
        type: object
        properties:
          snvs:
            type: string
          indels:
            type: string
        required:
          - snvs
          - indels
    required:
      - clines
      - vqsr
      - hard

  processing:
    type: object
    properties:
      remove-duplicates:
        type: boolean
      restrict-regions:
        type: string
      region-padding:
        type: integer
    required:
      - remove-duplicates

  params:
    type: object
    properties:
      subref:
        type: object
        properties:
          Scontigs:
            type: integer
          Sscaffold:
            type: integer
          Sep:
            type: integer
          TargetID:
            type: string
          NntargetID:
            type: string
      gatk:
        type: object
        properties:
          HaplotypeCaller:
            type: string
          BaseRecalibrator:
            type: string
          GenotypeGVCFs:
            type: string
          VariantRecalibrator:
            type: string
        required:
          - HaplotypeCaller
          - BaseRecalibrator
          - GenotypeGVCFs
          - VariantRecalibrator
      picard:
        type: object
        properties:
          MarkDuplicates:
            type: string
        required:
          - MarkDuplicates
    required:
      - gatk
      - picard

required:
  - samples
  - units
  - modules
  - ref
  - filtering
  - processing
  - params
