samples: /home/bo4spe/Littorina_saxatilis/short_genetic_variants/samples.tsv
units: /home/bo4spe/Littorina_saxatilis/short_genetic_variants/units.tsv
regions: /home/bo4spe/Littorina_saxatilis/short_genetic_variants/targets.region.list

modules:
  gatk: /home/bo4spe/modules/gatk-4.1.0.0/gatk
  bedt: /home/bo4spe/.conda/envs/short-variants/bin/bedtools
  pic: /home/bo4spe/.conda/envs/short-variants/share/picard-2.18.7-0/picard.jar
  eff: /home/bo4spe/.conda/envs/short-variants/share/snpeff-4.3.1t-0/snpEff.jar
  samt: /home/bo4spe/.conda/envs/short-variants/bin/samtools
  fbayes: /fastdata/bo4spe/freebayes
  vcflib: /fastdata/bo4spe/vcflib/bin
  samb: /home/bo4spe/.conda/envs/short-variants/bin/sambamba

rmdup: true

ref:
  genome: reference/Littorina_scaffolded_PacBio_run2_7_Oct_2016_unmasked.fasta
  subref: subreference/Lsax_subsuperref_run2_7_Oct_2016_unmasked.fasta

filtering:
  clines: --maf 0.1 --minQ 20 --max-missing-count 150
  # Set to true in order to apply machine learning based recalibration of
  # quality scores instead of hard filtering.
  vqsr: false
  hard:
    # hard filtering as outlined in GATK docs
    # (https://gatkforums.broadinstitute.org/gatk/discussion/2806/howto-apply-hard-filters-to-a-call-set)
    snvs:
      "QD < 2.0 || FS > 60.0 || MQ < 40.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0"
    indels:
      "QD < 2.0 || FS > 200.0 || ReadPosRankSum < -20.0 || InbreedingCoeff < -0.8 || SOR > 10.0"

processing:
  remove-duplicates: false
  # point to a bed file with e.g. captured regions if necessary,
  # see https://gatkforums.broadinstitute.org/gatk/discussion/4133/when-should-i-use-l-to-pass-in-a-list-of-intervals
  restrict-regions: joined_captured_supercontigs.bed
  # If regions are restricted, use this to enlarge them in order to include
  # flanking areas.
  region-padding: 100
  zone: "CZA"


params:
  subref:
    Scontigs: 1000
    Sscaffold: 400000
    Sep: 900
    TargetID: Supercontig
    NntargetID: Superscaffold
  gatk:
    HaplotypeCaller: ""
    BaseRecalibrator: ""
    GenotypeGVCFs: ""
    VariantRecalibrator: ""
    VariantsToTable: "depth,coverage"
  picard:
    MarkDuplicates: "REMOVE_DUPLICATES=true"
  trimmomatic:
    pe:
      trimmer:
        - "ILLUMINACLIP:adapters/adapt_cont.fa:2:30:10"
        - "LEADING:3"
        - "TRAILING:3"
        - "SLIDINGWINDOW:4:15"
        - "MINLEN:36"
    se:
      trimmer:
        - "ILLUMINACLIP:../raw/primers_adapters.fasta:2:30:10"
        - "LEADING:3"
        - "TRAILING:3"
        - "SLIDINGWINDOW:4:15"
        - "MINLEN:36"
  rstudio:
    ClineSide: "left, right"
